os:
  - osx
os_image: xcode9.2
rvm:
  - 2.4
script:
  - '
    cmd=    
    if [ -n "$BOXEN_GITHUB_TOKEN" ]; then
      echo "boxen github token...";
      cmd='./script/boxen --no-fde --stealth --no-pull --debug --profile --login $BOXEN_GITHUB_LOGIN --token $BOXEN_GITHUB_TOKEN';
    else
      echo "boxen github token...";
      cmd='./script/boxen --no-fde --stealth --no-pull --debug --profile';
  fi
  $cmd || test $? -eq 2;
'
  - source /opt/boxen/env.sh
  - bundle exec rspec spec
#before_install:
#  - rvm install 2.0.0
#  - rvm use 2.0.0
#  - gem install bundler -v '~> 1.10.5'
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_VERBOSE=1
